spring:
    profiles:
        active: dev
    mvc:
        pathmatch:
          matching-strategy: ant_path_matcher
    datasource:
      url: jdbc:mysql://mydb1.cewhikggzzlt.ap-northeast-2.rds.amazonaws.com:3306/carpool?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
      username: ubuntu
      password: 12341234
      driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
        #      show_sql: true
          format_sql: true
      # org.hibernate.type: trace

