name: build and deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        uses: gradle/wrapper-action@v2.6.0
        with:
          arguments: build

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: inha_carppool_server
          path: build/libs/inha_carppool_server-0.0.1-SNAPSHOT.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: inha_carppool_server
          path: build/libs/

      - name: Deploy to EC2
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          scp -i private_key.pem -o StrictHostKeyChecking=no -r build/libs/inha_carppool_server-0.0.1-SNAPSHOT.jar ${{ secrets.USER }}@${{ secrets.HOST }}:~/INHA_CARPOOL_SERVER/inhaCarPool_SERVER/build/libs/
          ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} "pgrep java | xargs kill -9; nohup java -jar ~/INHA_CARPOOL_SERVER/inhaCarPool_SERVER/build/libs/inha_carppool_server-0.0.1-SNAPSHOT.jar > ~/INHA_CARPOOL_SERVER/inhaCarPool_SERVER/build/libs/nohup.out 2>&1 &"
          rm -f private_key.pem



